# Add configuration to fix an issue where the `generate_all.php` script was outputting
# `Content-type: text/html` instead of `Content-type: application/zip`:

# - Recognize short opening tags, which are used in this project's php files.
short_open_tag = On
# - Enable output buffering.
output_buffering = On
